WITH ENCNTR_TYPES AS (
    SELECT ENCNTR_TYPE_ID,ENCNTR_TYPE_CD
    FROM CLN_ENCNTR_TYPE cet WHERE cet.SVC_CD ='TBC'
    AND cet.ENCNTR_TYPE_CD IN ('TBC_CONS','TBC_TREAT','TBC_IM_CONTACT','TBC_IM_REFERRAL','TBC_IM_SPECIAL','TBC_IM_CHEST','TBC_SKIN','TBC_SPEC','TBC_VAC')
),
SITES AS (
    SELECT SITE_ID,SITE_ENG_NAME 
    FROM CMN_SITE cs 
    WHERE cs.SVC_CD ='TBC' 
    AND cs.STATUS ='A' 
    AND nvl(cs.IS_MOCK_UP, 0) = 0
    AND (cs.EFFT_DATE IS NULL OR trunc(cs.EFFT_DATE) <= TRUNC(SYSDATE)) 
    AND (cs.EXPY_DATE IS NULL OR trunc(cs.EXPY_DATE) >= TRUNC(SYSDATE))
),
PERIOD_ENCOUNTER_FILTER AS (
    SELECT ce.SITE_ID,ce.PATIENT_KEY, ce.ENCNTR_TYPE_ID,ce.case_no 
    FROM CLC_ENCNTR ce
    WHERE ce.ENCNTR_STS <> 'D' AND nvl(ce.IS_CANCEL,0) <> 1 AND ce.SVC_CD='TBC' 
    AND ce.SDT >= to_date(:i_startDate,'yyyy-mm-dd') 
    and ce.SDT < to_date(:i_endDate,'yyyy-mm-dd')+1 
    AND ce.ENCNTR_TYPE_ID in (select ENCNTR_TYPE_ID from ENCNTR_TYPES)
    AND SITE_ID = decode(:i_siteId,'-',SITE_ID,:i_siteId)
),
PERIOD_ENCOUNTER AS (
    SELECT cs.SITE_ID,ce.case_no,ets.ENCNTR_TYPE_CD,ce.ENCNTR_TYPE_ID
    FROM PERIOD_ENCOUNTER_Filter ce
    INNER JOIN SITES cs ON cs.SITE_ID = ce.SITE_ID
    INNER JOIN PMI_PATIENT pp ON pp.PATIENT_KEY = ce.PATIENT_KEY AND nvl(pp.IS_MOCK_UP,0) = 0
    INNER JOIN ENCNTR_TYPES ets ON ets.ENCNTR_TYPE_ID = ce.ENCNTR_TYPE_ID
--    where ets.ENCNTR_TYPE_CD <> 'TBC_CONS' or ce.CASE_NO IS NOT NULL
),
TBC_CONS_ENCOUNTER_FILTER AS (
    SELECT ce.SITE_ID,ce.CASE_NO,ce.SDT,ce.PATIENT_KEY
    FROM CLC_ENCNTR ce
    WHERE ce.ENCNTR_STS <> 'D' 
    AND nvl(ce.IS_CANCEL,0) <> 1 
    AND ce.SVC_CD='TBC'
    AND ce.CASE_NO IS NOT NULL
    AND ce.ENCNTR_TYPE_ID in(select ENCNTR_TYPE_ID from ENCNTR_TYPES where ENCNTR_TYPE_CD ='TBC_CONS')
),
TBC_CONS_ENCOUNTER AS (
    SELECT ce.SITE_ID,ce.CASE_NO,ce.SDT
    FROM TBC_CONS_ENCOUNTER_FILTER ce
    INNER JOIN SITES cs ON cs.SITE_ID = ce.SITE_ID
    INNER JOIN PMI_PATIENT pp ON pp.PATIENT_KEY = ce.PATIENT_KEY AND nvl(pp.IS_MOCK_UP,0) = 0
),
FIRST_VISIT_TEMP AS (
    SELECT SITE_ID, count(1) AS FIRST_VISIT FROM (
        SELECT ce.*, ROW_NUMBER() OVER (PARTITION BY ce.CASE_NO ORDER BY ce.SDT ASC) AS NUM
        FROM TBC_CONS_ENCOUNTER ce
    )temp
    WHERE NUM = 1
    AND SDT >= to_date(:i_startDate,'yyyy-mm-dd') and SDT < to_date(:i_endDate,'yyyy-mm-dd')+1
    AND SITE_ID = decode(:i_siteId,'-',SITE_ID,:i_siteId)
    GROUP BY SITE_ID
)
--,PERIOD_ENCOUNTER_UNION as(
--    select SITE_ID,'TBC_CONS' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_CONS' AND CASE_NO IS NOT NULL
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_TREAT' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_TREAT'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_IM_CONTACT' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_IM_CONTACT'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_IM_REFERRAL' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_IM_REFERRAL'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_IM_SPECIAL' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_IM_SPECIAL'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_IM_CHEST' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_IM_CHEST'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_SKIN' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_SKIN'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_SPEC' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_SPEC'
--    group by SITE_ID
--    union all
--    select SITE_ID,'TBC_VAC' as ENCNTR_TYPE_CD,count(*) as counter from PERIOD_ENCOUNTER 
--    where ENCNTR_TYPE_CD = 'TBC_VAC'
--    group by SITE_ID
--), PERIOD_ENCOUNTER_COUNT as (
--    SELECT * from PERIOD_ENCOUNTER_UNION
--    PIVOT (
--        max(counter)
--      FOR ENCNTR_TYPE_CD in(
--      'TBC_CONS' AS TOTAL_CONS,'TBC_TREAT' AS RETURN_TREATMENT,'TBC_IM_CONTACT' AS IMAGE_CONTACT,'TBC_IM_REFERRAL' AS IMAGE_REFERRAL,
--      'TBC_IM_SPECIAL' AS IMAGE_SPECIAL,'TBC_IM_CHEST' AS IMAGE_TBCS,'TBC_SKIN' AS SKIN_IGRA,'TBC_SPEC' AS SPECIMEN_COLL,'TBC_VAC' AS VACC
--      )
--    )
--)
,PERIOD_ENCOUNTER_COUNT as(
    SELECT SITE_ID,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_CONS' AND CASE_NO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL_CONS,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_TREAT' THEN 1 ELSE 0 END) AS RETURN_TREATMENT,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_IM_CONTACT' THEN 1 ELSE 0 END) AS IMAGE_CONTACT,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_IM_REFERRAL' THEN 1 ELSE 0 END) AS IMAGE_REFERRAL,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_IM_SPECIAL' THEN 1 ELSE 0 END) AS IMAGE_SPECIAL,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_IM_CHEST' THEN 1 ELSE 0 END) AS IMAGE_TBCS,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_SKIN' THEN 1 ELSE 0 END) AS SKIN_IGRA,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_SPEC' THEN 1 ELSE 0 END) AS SPECIMEN_COLL,
    SUM(CASE WHEN ENCNTR_TYPE_CD = 'TBC_VAC' THEN 1 ELSE 0 END) AS VACC
    FROM PERIOD_ENCOUNTER WHERE SITE_ID = decode(:i_siteId,'-',SITE_ID,:i_siteId)
    GROUP BY SITE_ID
)
--select * from PERIOD_ENCOUNTER_COUNT
--order by site_id
--;
--select * from SITES cs
--LEFT JOIN FIRST_VISIT_TEMP ON FIRST_VISIT_TEMP.SITE_ID = cs.SITE_ID
--LEFT JOIN PERIOD_ENCOUNTER_COUNT ON PERIOD_ENCOUNTER_COUNT.SITE_ID =  cs.SITE_ID
--;

SELECT cs.SITE_ENG_NAME AS CENTRE,
nvl(FIRST_VISIT,0) AS FIRST_VISIT ,
nvl(TOTAL_CONS-nvl(FIRST_VISIT,0),0) AS RETURN_CONS ,
nvl(RETURN_TREATMENT,0) AS RETURN_TREATMENT,
nvl(IMAGE_CONTACT,0) AS IMAGE_CONTACT,
nvl(IMAGE_REFERRAL,0) AS IMAGE_REFERRAL,
nvl(IMAGE_SPECIAL,0) AS IMAGE_SPECIAL,
nvl(IMAGE_TBCS,0)  AS IMAGE_TBCS,
nvl(SKIN_IGRA,0) AS SKIN_IGRA,
nvl(SPECIMEN_COLL,0) AS SPECIMEN_COLL,
nvl(VACC,0) AS VACC,
nvl(TOTAL_CONS,0) + nvl(RETURN_TREATMENT,0) +  nvl(IMAGE_CONTACT,0) + nvl(IMAGE_REFERRAL,0) + nvl(IMAGE_SPECIAL,0) + nvl(IMAGE_TBCS,0) + nvl(SKIN_IGRA,0) + nvl(SPECIMEN_COLL,0) + nvl(VACC,0) AS GRAND_TOTAL
FROM SITES cs
LEFT JOIN FIRST_VISIT_TEMP ON FIRST_VISIT_TEMP.SITE_ID = cs.SITE_ID
LEFT JOIN PERIOD_ENCOUNTER_COUNT TEMP ON TEMP.SITE_ID =  cs.SITE_ID
WHERE cs.SITE_ID = decode(:i_siteId,'-',cs.SITE_ID,:i_siteId)
ORDER BY cs.SITE_ENG_NAME;